name: python-test

services:

  node:
    image: node:20-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: [ "npm" ]

  db:
    image: postgres:15-alpine
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-sail}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

  # --- SERVICE LARAVEL APP ---
  app:
    build: .
    container_name: laravel_app
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www
    networks:
      - laravel

  # --- SERVICE NGINX ---
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "4000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  # --- SERVICE PYTHON AI (PENCATAT KEUANGAN) ---
  api:
    cpu_shares: 90
    command: []
    container_name: script-pencatat-keuangan
    hostname: script-pencatat-keuangan
    image: ghcr.io/rahmadwidiansyah/script_pencatat_keuangan_api:v4
    deploy:
      resources:
        limits:
          memory: "1946157056"
    labels:
      icon: https://raw.githubusercontent.com/rahmadwidiansyah/script_pencatat_keuangan/refs/heads/main/logo.png
    ports:
      - mode: ingress
        target: 3987
        published: "3987"
        protocol: tcp
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - laravel

# --- KONFIGURASI NETWORK ---
networks:
  laravel:
    driver: bridge
    # name: python-test_default

# --- PERSISTENT STORAGE ---
volumes:
  db_data:

    # --- METADATA CASAOS ---
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/rahmadwidiansyah/script_pencatat_keuangan/refs/heads/main/logo.png
  index: /
  is_uncontrolled: false
  port_map: "3987"
  scheme: http
  title:
    custom: Pencatat Keuangan
