services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www
      - /var/www/vendor
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "4000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

# INI BAGIAN YANG KURANG TADI:
networks:
  laravel:
    driver: bridge
